# Generated by Django 2.2.7 on 2019-11-10 16:44

import django.core.validators
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('forecast_date', models.DateField(help_text='Date of forecast')),
                ('min_temp', models.FloatField(help_text='Minimum temperature in Celsius')),
                ('max_temp', models.FloatField(help_text='Maximum temperature in Celsius')),
                ('rainfall_mm', models.FloatField(help_text='Rainfall in MM', validators=[django.core.validators.MinValueValidator(0)])),
                ('wind_km', models.FloatField(help_text='Wind speed in km/h', validators=[django.core.validators.MinValueValidator(0)])),
                ('city', models.TextField(help_text='City for the forecast')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
